//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.09 at 07:38:30 AM COT 
//


package com.ericsson.cep.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericsson.cep.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EnvioSMSRequest_QNAME = new QName("http://claro.com.pe/eai/bs/xsd/postventa/EnvioSms", "EnvioSMSRequest");
    private final static QName _EnvioSMSResponse_QNAME = new QName("http://claro.com.pe/eai/bs/xsd/postventa/EnvioSms", "EnvioSMSResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericsson.cep.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnvioSMSRequestType }
     * 
     */
    public EnvioSMSRequestType createEnvioSMSRequestType() {
        return new EnvioSMSRequestType();
    }

    /**
     * Create an instance of {@link EnviarSmsResponse }
     * 
     */
    public EnviarSmsResponse createEnviarSmsResponse() {
        return new EnviarSmsResponse();
    }

    /**
     * Create an instance of {@link EnvioSMSResponseType }
     * 
     */
    public EnvioSMSResponseType createEnvioSMSResponseType() {
        return new EnvioSMSResponseType();
    }

    /**
     * Create an instance of {@link EnviarSms }
     * 
     */
    public EnviarSms createEnviarSms() {
        return new EnviarSms();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnvioSMSRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://claro.com.pe/eai/bs/xsd/postventa/EnvioSms", name = "EnvioSMSRequest")
    public JAXBElement<EnvioSMSRequestType> createEnvioSMSRequest(EnvioSMSRequestType value) {
        return new JAXBElement<EnvioSMSRequestType>(_EnvioSMSRequest_QNAME, EnvioSMSRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnvioSMSResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://claro.com.pe/eai/bs/xsd/postventa/EnvioSms", name = "EnvioSMSResponse")
    public JAXBElement<EnvioSMSResponseType> createEnvioSMSResponse(EnvioSMSResponseType value) {
        return new JAXBElement<EnvioSMSResponseType>(_EnvioSMSResponse_QNAME, EnvioSMSResponseType.class, null, value);
    }

}
