//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.09 at 07:38:30 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://claro.com.pe/eai/bs/xsd/postventa/EnvioSms", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ericsson.cep.wsdl;
